name: Fishing Alerts Workflow

on:
  schedule:
    - cron: '0 20 * * *'  # Runs daily at 8:00 PM UTC (7:00 PM BST)
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  run-fishing-alerts:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'  # Explicitly set Python version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests filelock
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Set environment variables
        run: |
          echo "FISH_LAT=52.414" >> $GITHUB_ENV
          echo "FISH_LON=-4.082" >> $GITHUB_ENV
          echo "FISH_TZ=Europe/London" >> $GITHUB_ENV
          echo "PUSHOVER_TOKEN=${{ secrets.PUSHOVER_TOKEN }}" >> $GITHUB_ENV
          echo "PUSHOVER_USER=${{ secrets.PUSHOVER_USER }}" >> $GITHUB_ENV
          echo "WORLDTIDES_KEY=${{ secrets.WORLDTIDES_KEY }}" >> $GITHUB_ENV

      - name: Run fishing alert script
        run: python fishing_alert.py
        env:
          PYTHONUNBUFFERED: 1  # Ensures logs are output in real-time

      - name: Check script exit code
        if: failure()
        run: |
          echo "Script failed. Please check the logs for details."
          exit 1

      - name: Upload state file (optional)
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: state
          path: state.json

      - name: Notify on failure (optional)
        if: failure()
        uses: slack/send@v3
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: fishing-alerts
          text: "Fishing Alerts Workflow failed on ${{ github.repository }}. Check run #${{ github.run_id }}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
