name: Fishing Alerts

on:
  schedule:
    # Runs every day at 07:30 London time (change if you prefer)
    - cron: "30 7 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert script
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER:  ${{ secrets.PUSHOVER_USER }}
          WORLDTIDES_KEY: ${{ secrets.WORLDTIDES_KEY }}  # optional
          FISH_LAT: "52.414"      # Aberystwyth
          FISH_LON: "-4.082"
          FISH_TZ:  "Europe/London"
        run: python fishing_alert.py

      - name: Commit updated state.json (if changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "Update alert state [skip ci]"
            git push
          else
            echo "No state changes."
          fi
